<?php

namespace App\Enum;

enum CallType: string
{
    case ABDUCTIO = 'ABDUCTION';
    case ABUSEABA = 'ABUSE ABANDONMENT NEGLECT';
    case ACCPRT = 'ACCIDENT (REPORT ONLY)';
    case ACCPD = 'ACCIDENT PD';
    case ALARM = 'ALARM COMPANY - POLICE';
    case ANIMAL = 'ANIMAL PROBLEM';
    case ASSLTIP = 'ASSAULT IN PROGRESS';
    case ASSAULT_REPORT = 'ASSAULT REPORT';
    case ASSLTSEX = 'ASSAULT SEXUAL';
    case ASSLTIJ = 'ASSAULT WITH INJURY (NOT IN PROGRESS)';
    case ATL = 'ATTEMPT TO LOCATE';
    case BOMBEXP = 'BOMB EXPLOSION';
    case BOMBFND = 'BOMB FOUND';
    case BOMBTHRT = 'BOMB THREAT';
    case BURGLARY = 'BURGLARY HOME INVASION';
    case BURGIP = 'BURGLARY IN PROGRESS';
    case BURG = 'BURGLARY REPORT';
    case CARJACK = 'CAR JACKING';
    case CONTSUBS = 'CONTROLLED SUBSTANCE';
    case DECEASED = 'DECEASED PERSON';
    case DIST = 'DISTURBANCE';
    case DISTDOME = 'DISTURBANCE - DOMESTIC';
    case DISTNOIS = 'DISTURBANCE - NOISE';
    case DISTURBN = 'DISTURBANCE NUISANCE';
    case DISTWEAP = 'DISTURBANCE W/WEAPON';
    case DOMESTIC = 'DOMESTIC DISTURBANCE VIOLENCE';
    case DUI = 'DRIVING UNDER THE INFLUENCE (IMPAIRED DRIVING)';
    case FBRUSH = 'GRASS, BRUSH, or OR TIMBER FIRE';
    case FCOALARM = 'CARBON MONOXIDE ALARM';
    case FCONFINE = 'CONFINED SPACE RESCUE';
    case FEXTRIC = 'EXTRICATION';
    case FHAZMAT = 'HAZ-MAT';
    case FIGHT = 'FIGHT';
    case FIGHTWEA = 'FIGHT W/WEAPON';
    case FNDPERS = 'FOUND PERSON';
    case FNDPROP = 'FOUND PROPERTY';
    case FNONSTR = 'NON-STRUCTURE FIRE';
    case FSTRUCT = 'STRUCTURE FIRE';
    case GUNSHOTS = 'GUNSHOTS REPORTED';
    case HARASSME = 'HARASSMENT STALKING THREAT';
    case HITRUN = 'HIT & RUN';
    case HITRUNIJ = 'HIT & RUN WITH INJURY';
    case HOMICID = 'HOMICIDE';
    case HOSTAGE = 'HOSTAGE';
    case INDECENC = 'INDECENCY LEWDNESS';
    case INDEXP = 'INDECENT EXPOSURE';
    case INTOXDRV = 'INTOXICATED DRIVER';
    case INTOXPER = 'INTOXICATED PERSON';
    case JUVENILE = 'JUVENILE TROUBLE';
    case KIDNAPIP = 'KIDNAPPING IN PROGRESS';
    case KIDNAP = 'KIDNAPPING REPORT';
    case MEDI = 'MEDICAL';
    case MISCELLA = 'MISCELLANEOUS';
    case MISSINGF = 'MISSING RUNAWAY FOUND PERSON';
    case NCORDER = 'NO CONTACT ORDER VIOLATION';
    case OTHER = 'OTHER';
    case OUTSIDEF = 'OUTSIDE FIRE';
    case PICKUP = 'PICKUP ITEM/PROPERTY';
    case PURSUITF = 'FOOT PURSUIT';
    case PURSUITV = 'VEHICLE PURSUIT';
    case RECKLESS = 'RECKLESS DRIVER';
    case RECOVERY = 'RECOVERY STOLEN VEHICLE';
    case ROBBERYC = 'ROBBERY CARJACKING';
    case ROBERYIP = 'ROBBERY IN PROGRESS';
    case ROBBERY = 'ROBBERY REPORT';
    case RUNAWAY = 'RUNAWAY';
    case SHOOTING = 'SHOOTING';
    case SRT = 'SRT CALL';
    case STABBING = 'STABBING';
    case STALLVEH = 'STALLED VEHICLE';
    case SUBJWEAP = 'SUBJECT WITH A WEAPON';
    case SUSPPKGB = 'SUSPICIOUS PACKAGE/BOMB THREAT';
    case SUSPPERS = 'SUSPICIOUS PERSON';
    case SUSPVEH = 'SUSPICIOUS VEHICLE';
    case SUSPICIO = 'SUSPICIOUS WANTED PERSON CIRCUMSTANCES VEHICLE';
    case THEFT = 'THEFT';
    case THEFTFRV = 'THEFT FROM VEHICLE';
    case THEFTIC = 'THEFT IN CUSTODY';
    case THEFTIP = 'THEFT IN PROGRESS';
    case THEFTVEH = 'THEFT OF VEHICLE';
    case TRAFFTOW = 'TOW VEHICLE';
    case TRAFFIC = 'TRAFFIC';
    case TRAFFHAZ = 'TRAFFIC HAZARD';
    case TS = 'TRAFFIC STOP';
    case TRAFFICA = 'TRAFFIC TRANSPORTATION ACCIDENT (CRASH)';
    case TRAFFICV = 'TRAFFIC VIOLATION';
    case TRESPASS = 'TRESPASSING UNWANTED';
    case TRBLUNK = 'TROUBLE UNKNOWN';
    case VEHICLEF = 'VEHICLE FIRE';
    case WATERRES = 'WATER RESCUE';
    case WATERCRA = 'WATERCRAFT IN DISTRESS';
    case WELFCHK = 'WELFARE CHECK';
    case TEST = 'TEST CALL';

    public static function options(): array
    {
        return array_column(self::cases(), 'value', 'name');
    }
}
